name: Artifact Export 

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    name: Artifact-Export 
    runs-on: ubuntu-latest
    steps:
      - name: Export 
        run: |
           git branch -vv && pwd && ls -la