name: Artifact Export 

on:
  pull_request:

jobs:
  build:
    name: Artifact-Export 
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Code
        uses: actions/checkout@v2
      - name: Setup KubeKey
        run: curl -sfL https://get-kk.kubesphere.io | sh -
      - name: Export
        run: sudo ./kk artifact export -m manifest.yaml